server:
  port: '@server.port@'
info:
  version: '@project.version@'
  stage: dev
spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: @db.url@
    username: @db.user@
    password: @db.password@
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 3
  flyway:
    schemas: @db.schema@

#будет удалено в будущем
hellgate:
  invoicing:
    url: http://localhost:8023/v1/invoicing
    timeout: 30000

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always
